spring:
  cache:
    type: REDIS
  datasource:
    url: jdbc:mysql://localhost:3306/es_mq_cache_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 172.16.199.126
    port: 6379
  activemq:
    broker-url: tcp:localhost:61616
    user: admin
    password: admin
server:
  port: 8088
debug: true
