spring:
  cache:
    type: REDIS
  datasource:
    url: jdbc:mysql://localhost:3306/es_mq_cache_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
server:
  port: 8088
debug: true
